# Generated by Django 2.2.6 on 2019-10-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anxiety_rating', models.IntegerField()),
                ('lifestyle_rating', models.IntegerField()),
                ('confidence_rating', models.IntegerField()),
                ('happy_rating', models.IntegerField()),
                ('survey_time', models.IntegerField(default=0)),
                ('survey_clicks', models.IntegerField(default=0)),
                ('survey_keypress', models.IntegerField(default=0)),
                ('survey_backspaces', models.IntegerField(default=0)),
                ('quote_replication', models.CharField(default='Knowing how to think empowers you far beyond those who know only what to think.', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='login_app.User')),
            ],
        ),
    ]
